version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - aa-memcached
      - aa-db
      - aa-db2
    depends_on:
      - aa-memcached
      - aa-db
      - aa-db2
    environment:
      MYSQL_USER: aladhan
      MYSQL_PASSWORD: aladhan
      MYSQL_DATABASE: aladhan_locations
      MYSQL_HOST: aa-db
      MYSQL_SLAVE_USER: aladhan
      MYSQL_SLAVE_PASSWORD: aladhan
      MYSQL_SLAVE_DATABASE: aladhan_locations
      MYSQL_SLAVE_HOST: aa-db2
      MEMCACHED_HOST: aa-memcached
      MEMCACHED_PORT: 11211
      GOOGLE_API_KEY: XYZ
      ASKGEO_ACCOUNT_ID: 123
      ASKGEO_API_KEY: ABC
    ports:
      - "7070:8080"
    volumes:
      - .:/var/www
    privileged: true
    container_name: aa-app


  #######################################
  # MySQL
  #######################################
  aa-db:
    image: vesica/api.aladhan.com-db:master
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: aladhan
      MYSQL_PASSWORD: aladhan
      MYSQL_DATABASE: aladhan_locations
    container_name: aa-db

  #######################################
  # MySQL2
  #######################################
  aa-db2:
    image: vesica/api.aladhan.com-db:master
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: aladhan
      MYSQL_PASSWORD: aladhan
      MYSQL_DATABASE: aladhan_locations
    container_name: aa-db2
  #######################################
  # PHPMyAdmin 1
  #######################################
  aa-pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: aa-db
    ports:
      - "7071:80"
    links:
      - aa-db-1
    depends_on:
      - aa-db-1
    container_name: aa-pma

  #######################################
  # Memcached
  #######################################
  aa-memcached:
    image: memcached:1.5
    #ports:
    #  - "11211:11211"
    container_name: aa-memcached

  #######################################
  # Memcached Admin
  #######################################
  aa-memadmin:
    image: vesica/memadmin:latest
    ports:
      - "7074:8080"
    environment:
      MEMADMIN_USERNAME: aa
      MEMADMIN_PASSWORD: aa
      MEMCACHED_HOST: aa-memcached
      MEMCACHED_PORT: 11211
    container_name: aa--memadmin
