version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - aa-memcached
      - aa-db
    depends_on:
      - aa-memcached
      - aa-db
    environment:
      MYSQL_USER: "aladhan"
      MYSQL_PASSWORD: "aladhan"
      MYSQL_DATABASE: "aladhan_locations"
      MYSQL_HOST: "aa-db"
      MYSQL_SLAVE_USER: "aladhan"
      MYSQL_SLAVE_PASSWORD: "aladhan"
      MYSQL_SLAVE_DATABASE: "aladhan_locations"
      MYSQL_SLAVE_HOST: "aa-db"
      MEMCACHED_HOST: "aa-memcached"
      MEMCACHED_PORT: 11211
      GOOGLE_API_KEY: "xyz"
      ASKGEO_ACCOUNT_ID: "1234"
      ASKGEO_API_KEY: "xyz"
    ports:
      - "7070:8080"
    volumes:
      - .:/var/www
    privileged: true
    container_name: aa-app


  #######################################
  # MySQL
  #######################################
  aa-db:
    build:
      context: db/master
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "aladhan"
      MYSQL_PASSWORD: "aladhan"
      MYSQL_DATABASE: "aladhan_locations"
    container_name: aa-db

  #######################################
  # PHPMyAdmin 1
  #######################################
  aa-pma:
    image: phpmyadmin/phpmyadmin:4.8.3
    environment:
      PMA_HOST: aa-db
    ports:
      - "7071:80"
    links:
      - aa-db
    depends_on:
      - aa-db
    container_name: aa-pma

  #######################################
  # Memcached
  #######################################
  aa-memcached:
    image: memcached:1.5
    #ports:
    #  - "11211:11211"
    container_name: aa-memcached

  #######################################
  # Memcached Admin
  #######################################
  aa-memadmin:
    image: vesica/memadmin:latest
    ports:
      - "7074:8080"
    environment:
      MEMADMIN_USERNAME: aa
      MEMADMIN_PASSWORD: aa
      MEMCACHED_HOST: aa-memcached
      MEMCACHED_PORT: 11211
    container_name: aa--memadmin
