# Note that values separated with a comma are always OR and each of the global keys are always AND
##### BLACKLIST #####
blacklist:
  - name: SEMRush and Bad Bots # required
    headers: # required
      request: # required HTTP_ appended
        X_FORWARDED_FOR: ["46.229.168.0/24", "197.234.242.0/24", "192.243.53.0/24", "192.145.239.34", "192.243.55.0/24"]
      server: # required
  - name: Knowmn abusers # required
    headers: # required
      request: # required HTTP_ appended
        X_FORWARDED_FOR: ["217.138.37.107", "31.167.60.182", "41.111.28.140", "115.51.10.242", "192.168.255.53"]
      server: # required


##### RATE LIMITING #####
ratelimit:
  - name: Malaysian IP # required
    headers: # required
      request: # required HTTP_ appended
        X_FORWARDED_FOR: ["210.195.111.90"]
        CLIENT_IP: ["210.195.111.90"]
      server: # required
    limit:
      rate: 600
      time: 3600 #60 = 1 minute, 3600 = 1 hour, 86400 = 1 day
  - name: Excessive empty requests IP # required
      headers: # required
        request: # required HTTP_ appended
          X_FORWARDED_FOR: ["35.185.190.11"]
        server: # required
      limit:
        rate: 300
        time: 600 #60 = 1 minute, 3600 = 1 hour, 86400 = 1 day



##### WHITELIST #####
whitelist:
- name: app-1-london # required
  headers: # required
    request: # required HTTP_ appended
      X_FORWARDED_FOR: ["178.79.155.249"]
    server: # required
