# Note that values separated with a comma are always OR and each of the global keys are always AND
##### BLACKLIST #####
blacklist:
  - name: SEMRush and Bad Bots # required
    headers: # required
      request: # required HTTP_ appended
        X_FORWARDED_FOR: ["46.229.168.0/24", "197.234.242.0/24", "192.243.53.0/24", "192.145.239.34", "192.243.55.0/24"]
      server: # required
  - name: Known abusers # required
    headers: # required
      request: # required HTTP_ appended
        X_FORWARDED_FOR: ["217.138.37.107", "31.167.60.182", "41.111.28.140", "115.51.10.242"]
      server: # required
        X_DUMMY: []


##### RATE LIMITING #####
ratelimit:
  - name: Bad requests
    headers:
      request:
        X_FORWARDED_FOR: []
      server:
        X_DUMMY: []
    limit:
      rate: 200 # limited to 300 requests every 10 minutes
      time: 600 #60 = 1 minute, 3600 = 1 hour, 86400 = 1 day
  - name: Sujod.com
    headers:
      request:
        X_FORWARDED_FOR: ["77.235.46.41"]
      server:
        REQUEST_URI: ["cityInfo", "addressInfo"]
    limit:
      rate: 500
      time: 86400 #60 = 1 minute, 3600 = 1 hour, 86400 = 1 day



##### WHITELIST #####
whitelist:
  - name: app-1-london
    headers:
      request:
        X_FORWARDED_FOR: ["178.79.155.249"]
      server:
        X_DUMMY: []
  - name: app-1-london
    headers:
      request:
        X_DUMMY: []
      server:
        REMOTE_ADDR: ["178.79.155.249"]